# Generated by Django 5.2.6 on 2025-09-15 21:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WifiPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('plan_type', models.CharField(choices=[('time', 'Time-based'), ('data', 'Data-based'), ('unlimited', 'Unlimited')], default='time', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Duration in minutes', null=True)),
                ('data_limit_mb', models.PositiveIntegerField(blank=True, help_text='Data limit in MB', null=True)),
                ('upload_speed_kbps', models.PositiveIntegerField(help_text='Upload speed in Kbps')),
                ('download_speed_kbps', models.PositiveIntegerField(help_text='Download speed in Kbps')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WiFi Plan',
                'verbose_name_plural': 'WiFi Plans',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='WifiUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('mac_address', models.CharField(blank=True, max_length=17)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('active', 'Active'), ('expired', 'Expired'), ('disabled', 'Disabled')], default='pending', max_length=20)),
                ('data_used_mb', models.PositiveIntegerField(default=0)),
                ('time_used_minutes', models.PositiveIntegerField(default=0)),
                ('plan_started_at', models.DateTimeField(blank=True, null=True)),
                ('plan_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('mikrotik_username', models.CharField(blank=True, max_length=50, unique=True)),
                ('mikrotik_password', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.wifiplan')),
            ],
            options={
                'verbose_name': 'WiFi User',
                'verbose_name_plural': 'WiFi Users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('mac_address', models.CharField(max_length=17)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('bytes_uploaded', models.BigIntegerField(default=0)),
                ('bytes_downloaded', models.BigIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='billing.wifiuser')),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'ordering': ['-started_at'],
            },
        ),
    ]
