# Generated by Django 5.2.6 on 2025-09-15 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NasClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nasname', models.CharField(max_length=128, unique=True)),
                ('shortname', models.CharField(max_length=32)),
                ('type', models.CharField(default='other', max_length=30)),
                ('ports', models.IntegerField(default=1812)),
                ('secret', models.CharField(max_length=60)),
                ('server', models.CharField(blank=True, max_length=64)),
                ('community', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'NAS Client',
                'verbose_name_plural': 'NAS Clients',
                'db_table': 'nas',
            },
        ),
        migrations.CreateModel(
            name='RadiusGroupReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(db_index=True, max_length=64)),
                ('attribute', models.CharField(max_length=32)),
                ('op', models.CharField(default=':=', max_length=2)),
                ('value', models.CharField(max_length=253)),
            ],
            options={
                'verbose_name': 'RADIUS Group Reply',
                'verbose_name_plural': 'RADIUS Group Replies',
                'db_table': 'radgroupreply',
            },
        ),
        migrations.CreateModel(
            name='RadiusPostAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('reply', models.CharField(max_length=32)),
                ('authdate', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'RADIUS Post Auth',
                'verbose_name_plural': 'RADIUS Post Auth',
                'db_table': 'radpostauth',
            },
        ),
        migrations.CreateModel(
            name='RadiusReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=64)),
                ('attribute', models.CharField(max_length=32)),
                ('op', models.CharField(default=':=', max_length=2)),
                ('value', models.CharField(max_length=253)),
            ],
            options={
                'verbose_name': 'RADIUS Reply',
                'verbose_name_plural': 'RADIUS Replies',
                'db_table': 'radreply',
            },
        ),
        migrations.CreateModel(
            name='RadiusAccounting',
            fields=[
                ('radacctid', models.AutoField(primary_key=True, serialize=False)),
                ('acctsessionid', models.CharField(db_index=True, max_length=64)),
                ('acctuniqueid', models.CharField(max_length=32, unique=True)),
                ('username', models.CharField(db_index=True, max_length=64)),
                ('groupname', models.CharField(blank=True, max_length=64)),
                ('realm', models.CharField(blank=True, max_length=64)),
                ('nasipaddress', models.GenericIPAddressField()),
                ('nasportid', models.CharField(blank=True, max_length=15)),
                ('nasporttype', models.CharField(blank=True, max_length=32)),
                ('acctstarttime', models.DateTimeField(blank=True, null=True)),
                ('acctupdatetime', models.DateTimeField(blank=True, null=True)),
                ('acctstoptime', models.DateTimeField(blank=True, null=True)),
                ('acctinterval', models.IntegerField(blank=True, null=True)),
                ('acctsessiontime', models.IntegerField(blank=True, null=True)),
                ('acctauthentic', models.CharField(blank=True, max_length=32)),
                ('connectinfo_start', models.CharField(blank=True, max_length=50)),
                ('connectinfo_stop', models.CharField(blank=True, max_length=50)),
                ('acctinputoctets', models.BigIntegerField(default=0)),
                ('acctoutputoctets', models.BigIntegerField(default=0)),
                ('calledstationid', models.CharField(blank=True, max_length=50)),
                ('callingstationid', models.CharField(blank=True, max_length=50)),
                ('acctterminatecause', models.CharField(blank=True, max_length=32)),
                ('servicetype', models.CharField(blank=True, max_length=32)),
                ('framedprotocol', models.CharField(blank=True, max_length=32)),
                ('framedipaddress', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'RADIUS Accounting',
                'verbose_name_plural': 'RADIUS Accounting',
                'db_table': 'radacct',
                'indexes': [models.Index(fields=['username'], name='radacct_usernam_4fd6da_idx'), models.Index(fields=['acctsessionid'], name='radacct_acctses_9f791e_idx'), models.Index(fields=['acctstarttime'], name='radacct_acctsta_69eee6_idx'), models.Index(fields=['acctstoptime'], name='radacct_acctsto_d45083_idx'), models.Index(fields=['nasipaddress'], name='radacct_nasipad_3f7fb7_idx')],
            },
        ),
        migrations.CreateModel(
            name='RadiusGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=64, unique=True)),
                ('attribute', models.CharField(max_length=32)),
                ('op', models.CharField(default=':=', max_length=2)),
                ('value', models.CharField(max_length=253)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wifi_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radius_groups', to='billing.wifiplan')),
            ],
            options={
                'verbose_name': 'RADIUS Group',
                'verbose_name_plural': 'RADIUS Groups',
                'db_table': 'radgroupcheck',
            },
        ),
        migrations.CreateModel(
            name='RadiusUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=64, unique=True)),
                ('attribute', models.CharField(default='Cleartext-Password', max_length=32)),
                ('op', models.CharField(default=':=', max_length=2)),
                ('value', models.CharField(max_length=253)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wifi_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radius_users', to='billing.wifiuser')),
            ],
            options={
                'verbose_name': 'RADIUS User',
                'verbose_name_plural': 'RADIUS Users',
                'db_table': 'radcheck',
            },
        ),
        migrations.CreateModel(
            name='RadiusUserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=64)),
                ('groupname', models.CharField(max_length=64)),
                ('priority', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'RADIUS User Group',
                'verbose_name_plural': 'RADIUS User Groups',
                'db_table': 'radusergroup',
                'unique_together': {('username', 'groupname')},
            },
        ),
    ]
