# Generated by Django 5.2.6 on 2025-09-16 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotik_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routerconfig',
            name='account_number',
            field=models.CharField(blank=True, help_text='KCB Account Number', max_length=50),
        ),
        migrations.AddField(
            model_name='routerconfig',
            name='business_name',
            field=models.CharField(blank=True, help_text='Business name for this station', max_length=100),
        ),
        migrations.AddField(
            model_name='routerconfig',
            name='enable_payments',
            field=models.BooleanField(default=True, help_text='Enable payments for this station'),
        ),
        migrations.AddField(
            model_name='routerconfig',
            name='kcb_api_key',
            field=models.CharField(blank=True, help_text='KCB Buni API Key', max_length=200),
        ),
        migrations.AddField(
            model_name='routerconfig',
            name='kcb_client_id',
            field=models.CharField(blank=True, help_text='KCB Buni Client ID', max_length=100),
        ),
        migrations.AddField(
            model_name='routerconfig',
            name='kcb_client_secret',
            field=models.CharField(blank=True, help_text='KCB Buni Client Secret', max_length=200),
        ),
        migrations.AddField(
            model_name='routerconfig',
            name='paybill_number',
            field=models.CharField(blank=True, help_text='KCB Buni Paybill Number', max_length=20),
        ),
        migrations.AddField(
            model_name='routerconfig',
            name='payment_method',
            field=models.CharField(choices=[('paybill', 'Paybill'), ('till', 'Buy Goods Till'), ('account', 'Bank Account')], default='paybill', max_length=20),
        ),
        migrations.AddField(
            model_name='routerconfig',
            name='till_number',
            field=models.CharField(blank=True, help_text='Buy Goods Till Number (alternative to paybill)', max_length=20),
        ),
    ]
