# Generated by Django 5.2.6 on 2025-09-16 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotik_integration', '0002_routerconfig_account_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routerconfig',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='routerconfig',
            name='kcb_api_key',
        ),
        migrations.RemoveField(
            model_name='routerconfig',
            name='kcb_client_id',
        ),
        migrations.RemoveField(
            model_name='routerconfig',
            name='kcb_client_secret',
        ),
        migrations.RemoveField(
            model_name='routerconfig',
            name='paybill_number',
        ),
        migrations.RemoveField(
            model_name='routerconfig',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='routerconfig',
            name='till_number',
        ),
        migrations.AddField(
            model_name='routerconfig',
            name='account_name',
            field=models.CharField(blank=True, help_text='Account holder name (for reference)', max_length=100),
        ),
        migrations.AddField(
            model_name='routerconfig',
            name='kcb_account_number',
            field=models.CharField(blank=True, help_text='KCB Paybill Number or Bank Account Number', max_length=50),
        ),
        migrations.AddField(
            model_name='routerconfig',
            name='kcb_account_type',
            field=models.CharField(choices=[('paybill', 'KCB Paybill'), ('account', 'KCB Bank Account')], default='paybill', help_text='Type of KCB account', max_length=20),
        ),
    ]
