# Generated by Django 5.2.6 on 2025-09-16 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotik_integration', '0003_remove_routerconfig_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routerconfig',
            name='account_number',
            field=models.CharField(blank=True, help_text='Legacy account number field', max_length=50),
        ),
        migrations.AddField(
            model_name='routerconfig',
            name='paybill_number',
            field=models.CharField(blank=True, help_text='Legacy paybill number field', max_length=50),
        ),
        migrations.AddField(
            model_name='routerconfig',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('paybill', 'Paybill'), ('till', 'Till Number'), ('account', 'Bank Account')], default='paybill', help_text='Payment method (legacy)', max_length=20),
        ),
        migrations.AddField(
            model_name='routerconfig',
            name='till_number',
            field=models.CharField(blank=True, help_text='Legacy till number field', max_length=50),
        ),
        migrations.AlterField(
            model_name='routerconfig',
            name='kcb_account_type',
            field=models.CharField(choices=[('paybill', 'Paybill Number'), ('till', 'Till Number'), ('bank', 'Bank Account')], default='paybill', help_text='Type of KCB account', max_length=20),
        ),
    ]
